"""Built-in subagent configurations."""

from .bash_agent import BASH_AGENT_CONFIG
from .cer_intake_agents import CER_INTAKE_COMPLIANCE_REVIEWER_CONFIG, CER_INTAKE_DOCUMENT_ANALYST_CONFIG
from .cer_review_agents import (
    CER_ADMIN_PRECHECK_REVIEWER_CONFIG,
    CER_CEAR_FORMATTER_REVIEWER_CONFIG,
    CER_CEP_METHODOLOGY_REVIEWER_CONFIG,
    CER_CLINICAL_EVIDENCE_PANEL_REVIEWER_CONFIG,
    CER_GATE_CLOSURE_REVIEWER_CONFIG,
    CER_HUMAN_BOUNDARY_REVIEWER_CONFIG,
    CER_IFU_SSCP_LABEL_REVIEWER_CONFIG,
    CER_INTAKE_REVIEWER_CONFIG,
    CER_INTENDED_PURPOSE_REVIEWER_CONFIG,
    CER_QA_GATE_REVIEWER_CONFIG,
    CER_QMS_REVIEWER_CONFIG,
    CER_STRUCTURE_COMPLIANCE_REVIEWER_CONFIG,
)
from .general_purpose import GENERAL_PURPOSE_CONFIG
from .rmf_review_agents import (
    RMF_CER_LINKAGE_REVIEWER_CONFIG,
    RMF_DIMENSION_REVIEWER_CONFIG,
    RMF_GATE_CLOSURE_REVIEWER_CONFIG,
    RMF_HUMAN_BOUNDARY_REVIEWER_CONFIG,
    RMF_INTAKE_REVIEWER_CONFIG,
    RMF_PARSE_NORMALIZE_REVIEWER_CONFIG,
    RMF_PRECHECK_REVIEWER_CONFIG,
    RMF_REPORT_REVIEWER_CONFIG,
)

__all__ = [
    "GENERAL_PURPOSE_CONFIG",
    "BASH_AGENT_CONFIG",
    "CER_INTAKE_DOCUMENT_ANALYST_CONFIG",
    "CER_INTAKE_COMPLIANCE_REVIEWER_CONFIG",
    "CER_INTAKE_REVIEWER_CONFIG",
    "CER_STRUCTURE_COMPLIANCE_REVIEWER_CONFIG",
    "CER_INTENDED_PURPOSE_REVIEWER_CONFIG",
    "CER_CEP_METHODOLOGY_REVIEWER_CONFIG",
    "CER_CLINICAL_EVIDENCE_PANEL_REVIEWER_CONFIG",
    "CER_IFU_SSCP_LABEL_REVIEWER_CONFIG",
    "CER_QA_GATE_REVIEWER_CONFIG",
    "CER_CEAR_FORMATTER_REVIEWER_CONFIG",
    "CER_HUMAN_BOUNDARY_REVIEWER_CONFIG",
    "CER_GATE_CLOSURE_REVIEWER_CONFIG",
    "CER_QMS_REVIEWER_CONFIG",
    "CER_ADMIN_PRECHECK_REVIEWER_CONFIG",
    "RMF_INTAKE_REVIEWER_CONFIG",
    "RMF_PARSE_NORMALIZE_REVIEWER_CONFIG",
    "RMF_PRECHECK_REVIEWER_CONFIG",
    "RMF_DIMENSION_REVIEWER_CONFIG",
    "RMF_HUMAN_BOUNDARY_REVIEWER_CONFIG",
    "RMF_REPORT_REVIEWER_CONFIG",
    "RMF_GATE_CLOSURE_REVIEWER_CONFIG",
    "RMF_CER_LINKAGE_REVIEWER_CONFIG",
]

# Registry of built-in subagents
BUILTIN_SUBAGENTS = {
    "general-purpose": GENERAL_PURPOSE_CONFIG,
    "bash": BASH_AGENT_CONFIG,
    "cer-intake-document-analyst": CER_INTAKE_DOCUMENT_ANALYST_CONFIG,
    "cer-intake-compliance-reviewer": CER_INTAKE_COMPLIANCE_REVIEWER_CONFIG,
    "cer-intake-reviewer": CER_INTAKE_REVIEWER_CONFIG,
    "cer-structure-compliance-reviewer": CER_STRUCTURE_COMPLIANCE_REVIEWER_CONFIG,
    "cer-intended-purpose-reviewer": CER_INTENDED_PURPOSE_REVIEWER_CONFIG,
    "cer-cep-methodology-reviewer": CER_CEP_METHODOLOGY_REVIEWER_CONFIG,
    "cer-clinical-evidence-panel-reviewer": CER_CLINICAL_EVIDENCE_PANEL_REVIEWER_CONFIG,
    "cer-ifu-sscp-label-reviewer": CER_IFU_SSCP_LABEL_REVIEWER_CONFIG,
    "cer-qa-gate-reviewer": CER_QA_GATE_REVIEWER_CONFIG,
    "cer-cear-formatter-reviewer": CER_CEAR_FORMATTER_REVIEWER_CONFIG,
    "cer-human-boundary-reviewer": CER_HUMAN_BOUNDARY_REVIEWER_CONFIG,
    "cer-gate-closure-reviewer": CER_GATE_CLOSURE_REVIEWER_CONFIG,
    "cer-qms-reviewer": CER_QMS_REVIEWER_CONFIG,
    "cer-admin-precheck-reviewer": CER_ADMIN_PRECHECK_REVIEWER_CONFIG,
    "rmf-intake-reviewer": RMF_INTAKE_REVIEWER_CONFIG,
    "rmf-parse-normalize-reviewer": RMF_PARSE_NORMALIZE_REVIEWER_CONFIG,
    "rmf-precheck-reviewer": RMF_PRECHECK_REVIEWER_CONFIG,
    "rmf-dimension-reviewer": RMF_DIMENSION_REVIEWER_CONFIG,
    "rmf-human-boundary-reviewer": RMF_HUMAN_BOUNDARY_REVIEWER_CONFIG,
    "rmf-report-reviewer": RMF_REPORT_REVIEWER_CONFIG,
    "rmf-gate-closure-reviewer": RMF_GATE_CLOSURE_REVIEWER_CONFIG,
    "rmf-cer-linkage-reviewer": RMF_CER_LINKAGE_REVIEWER_CONFIG,
}
