"""CER Writer Remediation Gates — W1 Gate 1 + Gate 3 + W2 Gate 2 + Gate 4.

These gates run AFTER the Writer produces CER body text (markdown) and BEFORE
the draft is committed to the output/final directory.

Gate 1 — Device Identity Body Consistency Gate
Gate 2 — IFU Fact Consumption Gate
Gate 3 — Evidence-to-Conclusion Consistency Gate
Gate 4 — Submission Body Cleanliness Gate

CCD | 2026-05-15 | W1 implementation — Claude Code
"""

from __future__ import annotations

import json
import os
import re
from typing import Any

from .domain_term_matrix import (
    DOMAIN_TERM_MATRIX,
    resolve_domain,
    get_forbidden_terms,
    get_exception_contexts,
    get_ambiguous_terms,
    get_required_terms,
)
from .evidence_conclusion_policy import (
    resolve_policy_level,
    get_forbidden_phrases,
    scan_for_forbidden_phrases,
    INSUFFICIENT_ALIASES,
)

# ── Gate 4: Banned internal strings ────────────────────────────────────────

BANNED_INTERNAL_STRINGS: list[str] = [
    "Claude",
    "DeerFlow",
    "MCP",
    "score: 100",
    "benchmark decision",
    "Generated by cer_authoring",
    "internal tool trace",
    "gate trace",
    "Knowledge-base guidance",
    "Selected module",
    "writer_modules",
    "Required source inputs",
    "trigger:",
    "trigger_signals",
    "subagent_invocation_log",
    "routing_policy",
    "gate_debug",
    "model_routing_source",
    "cer_authoring_v1",
    "ALLOWED_USE_BLOCKED",
    "quantitative_or_source-reported:",
    "authoring run",
    "writing-evidence-table",
    "WET / writing-evidence-table",
    # V2 W-05 hardening: additional banned patterns
    "SKILL REFERENCE",
    "PLANNER AGENT",
    "IMPLEMENTER AGENT",
    "REVIEWER AGENT",
    "workbuddy",
    "checkpoint",
    "execution trace",
    "subagent communication",
    "delegation log",
    "agent handoff",
]

# ── Gate 2: IFU placeholder patterns ───────────────────────────────────────

IFU_PLACEHOLDER_PATTERNS: list[str] = [
    "Not extracted from IFU source text",
    "not extracted from IFU source text",
    "Not extracted from IFU",
    "Manufacturer not extracted from IFU",
    # V2 W-05 hardening: additional placeholder variants
    "IFU text not available",
    "source text unavailable",
    "extraction failed for",
    "pending IFU confirmation",
    "requires manual extraction",
]


# ── Gate 1: Device Identity Body Consistency ────────────────────────────────


def evaluate_device_domain_consistency_gate(
    cer_body_text: str,
    device_profile: dict[str, Any] | None,
) -> dict[str, Any]:
    """Gate 1: Scan CER body for forbidden terms from the device's domain.

    Args:
        cer_body_text: Full CER markdown body text.
        device_profile: device_profile.json content.

    Returns:
        Gate result dict with status, findings, and quarantine routing info.
    """
    if not cer_body_text.strip():
        return {
            "gate": "Gate 1 — Device Domain Consistency",
            "gate_id": "WRITER_GATE_01",
            "status": "HARD_FAIL",
            "reason": "CER body text is empty; final-body domain consistency cannot be verified.",
            "findings": [{
                "type": "empty_final_body",
                "severity": "HARD_FAIL",
                "message": "Writer produced no submission-facing CER body.",
            }],
            "warnings": [],
            "quarantine": True,
            "message": "HARD_FAIL: CER body text is empty.",
        }

    if not device_profile:
        return {
            "gate": "Gate 1 — Device Domain Consistency",
            "gate_id": "WRITER_GATE_01",
            "status": "SKIPPED",
            "reason": "No device_profile available; cannot resolve domain.",
            "findings": [],
            "warnings": [],
            "quarantine": False,
        }

    device_domain = device_profile.get("device_domain") or device_profile.get("clinical_domain") or ""
    domain_key = resolve_domain(device_domain)

    if not domain_key:
        return {
            "gate": "Gate 1 — Device Domain Consistency",
            "gate_id": "WRITER_GATE_01",
            "status": "BLOCKED",
            "reason": f"Unrecognised device_domain '{device_domain}'; cannot map to domain term matrix. Domain must be registered in DEVICE_DOMAIN_TO_MATRIX_DOMAIN before Writer can run.",
            "device_domain": device_domain,
            "findings": [{
                "finding_id": "DOMAIN-UNREGISTERED-001",
                "severity": "CRITICAL",
                "message": f"Device domain '{device_domain}' is not registered in the domain term matrix. Writer QA Gate 1 cannot validate domain consistency.",
                "remediation": f"Add '{device_domain}' to DEVICE_DOMAIN_TO_MATRIX_DOMAIN in domain_term_matrix.py.",
            }],
            "warnings": [],
            "quarantine": True,
        }

    domain_entry = DOMAIN_TERM_MATRIX.get(domain_key, {})
    forbidden_terms = get_forbidden_terms(domain_key)
    exception_contexts = get_exception_contexts(domain_key)
    ambiguous_terms = get_ambiguous_terms(domain_key)
    required_terms = get_required_terms(domain_key)

    # Split CER body: skip Annex sections for Gate 1 scan
    annex_marker = _find_annex_boundary(cer_body_text)
    scan_text = cer_body_text[:annex_marker] if annex_marker > 0 else cer_body_text

    findings: list[dict] = []
    warnings: list[dict] = []
    hard_fail = False

    # ── Forbidden terms scan ──
    scan_lower = scan_text.lower()
    for term in forbidden_terms:
        term_lower = term.lower()
        pos = 0
        while True:
            idx = scan_lower.find(term_lower, pos)
            if idx == -1:
                break
            surrounding = scan_text[max(0, idx - 200):idx + len(term) + 200]
            in_exception = _is_exception_context(surrounding, term_lower, exception_contexts)
            section = _guess_section(scan_text, idx)

            if not in_exception:
                findings.append({
                    "term": term,
                    "position": idx,
                    "section": section,
                    "surrounding_text": surrounding.strip()[:200],
                    "in_exception_context": False,
                })
                hard_fail = True
                break  # First HARD FAIL stops the scan per spec
            pos = idx + 1

        if hard_fail:
            break

    # ── Ambiguous terms scan (warnings only, never HARD FAIL) ──
    if not hard_fail:
        for term in ambiguous_terms:
            term_lower = term.lower()
            if term_lower in scan_lower:
                warnings.append({
                    "type": "ambiguous_term",
                    "term": term,
                    "message": f"Ambiguous term '{term}' found without sufficient required-term context.",
                })

    # ── Required terms coverage check (warnings only) ──
    if not hard_fail and required_terms:
        matched = sum(1 for t in required_terms if t.lower() in scan_lower)
        match_rate = matched / len(required_terms) if required_terms else 1.0
        if match_rate < 0.30:
            warnings.append({
                "type": "required_term_coverage",
                "match_rate": round(match_rate, 2),
                "matched": matched,
                "total": len(required_terms),
                "message": f"Required term match rate {match_rate:.0%} < 30%; possible domain mismatch.",
            })

    return {
        "gate": "Gate 1 — Device Domain Consistency",
        "gate_id": "WRITER_GATE_01",
        "status": "HARD_FAIL" if hard_fail else "PASS",
        "domain_key": domain_key,
        "device_domain": device_domain,
        "device_name": device_profile.get("device_name", "unknown"),
        "forbidden_terms_scanned": len(forbidden_terms),
        "findings": findings,
        "warnings": warnings,
        "quarantine": hard_fail,
        "message": (
            f"HARD_FAIL: {len(findings)} forbidden term(s) found in non-exception context."
            if hard_fail
            else f"PASS: No forbidden terms in non-exception context. {len(warnings)} warning(s)."
        ),
    }


# ── Gate 3: Evidence-to-Conclusion Consistency ─────────────────────────────


def evaluate_evidence_conclusion_gate(
    cer_body_text: str,
    claim_support_matrix: dict[str, Any] | None,
) -> dict[str, Any]:
    """Gate 3: Verify Summary/Conclusion phrasing matches claim support levels.

    Checks that forbidden phrases for each claim's support_level do NOT appear
    in the Summary and Conclusions sections unless negated.
    """
    if not claim_support_matrix:
        return {
            "gate": "Gate 3 — Evidence-Conclusion Consistency",
            "gate_id": "WRITER_GATE_03",
            "status": "SKIPPED",
            "reason": "No claim_support_matrix available.",
            "findings": [],
            "quarantine": False,
        }

    # Determine the most restrictive support_level across all claims
    # If ANY claim is INSUFFICIENT, apply INSUFFICIENT policy to the whole conclusion.
    worst_level = _worst_support_level(claim_support_matrix)

    if worst_level is None:
        return {
            "gate": "Gate 3 — Evidence-Conclusion Consistency",
            "gate_id": "WRITER_GATE_03",
            "status": "SKIPPED",
            "reason": "No recognisable support_level found in claim_support_matrix.",
            "findings": [],
            "quarantine": False,
        }

    policy_level = resolve_policy_level(worst_level)
    if not policy_level:
        return {
            "gate": "Gate 3 — Evidence-Conclusion Consistency",
            "gate_id": "WRITER_GATE_03",
            "status": "SKIPPED",
            "reason": f"Cannot resolve policy level for '{worst_level}'.",
            "findings": [],
            "quarantine": False,
        }

    forbidden_phrases = get_forbidden_phrases(policy_level)
    if not forbidden_phrases:
        return {
            "gate": "Gate 3 — Evidence-Conclusion Consistency",
            "gate_id": "WRITER_GATE_03",
            "status": "PASS",
            "policy_level": policy_level,
            "worst_support_level": worst_level,
            "message": "STRONG level — no forbidden phrases; automatic PASS.",
            "findings": [],
            "quarantine": False,
        }

    # Extract Summary and Conclusions sections
    summary_text = _extract_section(cer_body_text, "SUMMARY") or ""
    conclusions_text = _extract_section(cer_body_text, "CONCLUSIONS") or ""
    # Also scan §4.x claim-specific conclusions
    device_eval_text = _extract_section(cer_body_text, "DEVICE UNDER EVALUATION") or ""

    combined = f"{summary_text}\n{conclusions_text}\n{device_eval_text}"

    all_findings = scan_for_forbidden_phrases(combined, forbidden_phrases)
    hard_fail_findings = [f for f in all_findings if f["triggers_fail"]]
    negated_findings = [f for f in all_findings if f["negated"]]

    hard_fail = len(hard_fail_findings) > 0

    return {
        "gate": "Gate 3 — Evidence-Conclusion Consistency",
        "gate_id": "WRITER_GATE_03",
        "status": "HARD_FAIL" if hard_fail else "PASS",
        "policy_level": policy_level,
        "worst_support_level": worst_level,
        "forbidden_phrases_scanned": len(forbidden_phrases),
        "total_matches": len(all_findings),
        "hard_fail_count": len(hard_fail_findings),
        "negated_pass_count": len(negated_findings),
        "findings": hard_fail_findings,
        "negated_findings": negated_findings,
        "quarantine": hard_fail,
        "message": (
            f"HARD_FAIL: {len(hard_fail_findings)} forbidden phrase(s) found in conclusion text "
            f"without negation (policy level: {policy_level})."
            if hard_fail
            else f"PASS: No un-negated forbidden phrases in conclusion text "
                 f"(policy level: {policy_level}, {len(negated_findings)} negated match(es) allowed)."
        ),
    }


# ── Gate 2: IFU Fact Consumption Gate ──────────────────────────────────────


def evaluate_ifu_consumption_gate(
    cer_body_text: str,
    device_profile: dict[str, Any] | None,
) -> dict[str, Any]:
    """Gate 2: Check that IFU data was consumed, not placeholdered.

    Scans for 'Not extracted from IFU source text' patterns. If the device_profile
    shows IFU sources exist, these placeholders → GATE FAIL.
    """
    if not device_profile:
        return {
            "gate": "Gate 2 — IFU Fact Consumption",
            "gate_id": "WRITER_GATE_02",
            "status": "SKIPPED",
            "reason": "No device_profile available.",
            "findings": [],
            "quarantine": False,
        }

    profile_source_ids = device_profile.get("profile_source_ids") or device_profile.get("identity_supporting_source_types") or []
    has_ifu_source = bool(profile_source_ids)

    findings: list[dict] = []
    for pattern in IFU_PLACEHOLDER_PATTERNS:
        pos = 0
        while True:
            idx = cer_body_text.find(pattern, pos)
            if idx == -1:
                break
            findings.append({
                "pattern": pattern,
                "position": idx,
                "surrounding_text": cer_body_text[max(0, idx - 40):idx + len(pattern) + 40].strip(),
            })
            pos = idx + 1

    unique_fields = len({f.get("surrounding_text", "")[:40] for f in findings})
    hard_fail = has_ifu_source and len(findings) > 0

    return {
        "gate": "Gate 2 — IFU Fact Consumption",
        "gate_id": "WRITER_GATE_02",
        "status": "HARD_FAIL" if hard_fail else "PASS",
        "has_ifu_source": has_ifu_source,
        "placeholder_count": len(findings),
        "findings": findings,
        "quarantine": hard_fail,
        "message": (
            f"HARD_FAIL: {len(findings)} IFU placeholder(s) found despite available IFU source data."
            if hard_fail
            else f"PASS: {'No IFU placeholders found' if not findings else 'IFU placeholders acceptable — no IFU source available'}."
        ),
    }


# ── Gate 4: Submission Body Cleanliness ─────────────────────────────────────


def evaluate_body_cleanliness_gate(
    cer_body_text: str,
) -> dict[str, Any]:
    """Gate 4: Scan CER body for banned internal system language strings.

    These strings must NEVER appear in the submission-facing CER body.
    Annex sections are excluded from the scan (structural headings like
    'Annex J MCP Execution...' are template boilerplate, not leakage).
    """
    if not cer_body_text.strip():
        return {
            "gate": "Gate 4 — Submission Body Cleanliness",
            "gate_id": "WRITER_GATE_04",
            "status": "HARD_FAIL",
            "banned_strings_scanned": len(BANNED_INTERNAL_STRINGS),
            "finding_count": 1,
            "findings": [{
                "type": "empty_final_body",
                "severity": "HARD_FAIL",
                "message": "Writer produced no submission-facing CER body.",
            }],
            "quarantine": True,
            "message": "HARD_FAIL: CER body text is empty.",
        }

    # Exclude Annex sections from scan
    annex_marker = _find_annex_boundary(cer_body_text)
    scan_text = cer_body_text[:annex_marker] if annex_marker > 0 else cer_body_text

    findings: list[dict] = []
    for banned in BANNED_INTERNAL_STRINGS:
        pos = 0
        banned_lower = banned.lower()
        text_lower = scan_text.lower()
        while True:
            idx = text_lower.find(banned_lower, pos)
            if idx == -1:
                break
            findings.append({
                "banned_string": banned,
                "position": idx,
                "surrounding_text": scan_text[max(0, idx - 40):idx + len(banned) + 40].strip(),
            })
            pos = idx + 1

    hard_fail = len(findings) > 0

    return {
        "gate": "Gate 4 — Submission Body Cleanliness",
        "gate_id": "WRITER_GATE_04",
        "status": "HARD_FAIL" if hard_fail else "PASS",
        "banned_strings_scanned": len(BANNED_INTERNAL_STRINGS),
        "finding_count": len(findings),
        "findings": findings,
        "quarantine": hard_fail,
        "message": (
            f"HARD_FAIL: {len(findings)} banned internal string(s) found in CER body."
            if hard_fail
            else f"PASS: No banned internal strings in CER body."
        ),
    }


# ── Gate 5: Render Boundary + Context Contamination Trace ────────────────────


RENDER_BOUNDARY_PATTERNS: list[str] = [
    "Do NOT write",
    "DO NOT WRITE",
    "You are a medical writer",
    "Writer instruction:",
    "Writer template selector:",
    "Selected module:",
    "writer_modules",
    "Required source inputs:",
    "trigger_signals",
    "subagent_invocation_log",
    "routing_policy_v1",
    "gate_debug",
    "model_routing_source",
    "cer_authoring_v1",
    "authoring run configuration",
    "_mcp",
    "mcp_call_log",
    "lead_decisions",
    "rework_queue",
    "gate_routing_trace",
    "AP/human CER writing paradigm",
    "Knowledge-base guidance",
]


def evaluate_render_boundary_gate(cer_body_text: str) -> dict[str, Any]:
    """Gate 5: Detect internal metadata leakage in the rendered CER body."""
    findings = []
    for pattern in RENDER_BOUNDARY_PATTERNS:
        if pattern in cer_body_text:
            line_idx = cer_body_text.index(pattern)
            context = cer_body_text[max(0, line_idx - 40):line_idx + len(pattern) + 60]
            findings.append({
                "pattern": pattern,
                "context": context.strip()[:200],
                "severity": "HARD_FAIL",
            })
    hard_fail = len(findings) > 0
    return {
        "gate": "Gate 5 — Render Boundary",
        "gate_id": "WRITER_GATE_05",
        "status": "HARD_FAIL" if hard_fail else "PASS",
        "patterns_scanned": len(RENDER_BOUNDARY_PATTERNS),
        "finding_count": len(findings),
        "findings": findings,
        "quarantine": hard_fail,
        "message": (
            f"HARD_FAIL: {len(findings)} internal metadata pattern(s) leaked into CER body."
            if hard_fail
            else "PASS: No internal metadata in CER body."
        ),
    }


def build_context_contamination_trace(
    cer_body_text: str,
    device_profile: dict[str, Any] | None,
    state: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build CONTEXT_CONTAMINATION_TRACE for every forbidden term found in CER."""
    state = state or {}
    trace_entries: list[dict[str, Any]] = []
    if not device_profile:
        return {"entries": [], "forbidden_term_count": 0}
    domain = device_profile.get("device_domain") or device_profile.get("clinical_domain") or ""
    domain_key = resolve_domain(domain)
    if not domain_key:
        return {"entries": [], "forbidden_term_count": 0}
    forbidden_terms = get_forbidden_terms(domain_key)
    for term in forbidden_terms:
        if term.lower() not in cer_body_text.lower():
            continue
        origin = "unknown/model_generation"
        source_texts = [
            str(state.get("device_profile", {}).get("intended_purpose", "")),
            str(state.get("device_profile", {}).get("mode_of_action", "")),
        ]
        for item in state.get("source_inventory") or []:
            source_texts.append(str(item.get("text") or ""))
        for item in state.get("search_run_registry") or []:
            source_texts.append(str(item.get("query") or ""))
        for row in state.get("sota_benchmark_matrix") or []:
            source_texts.append(str(row.get("endpoint") or ""))
        combined = " ".join(source_texts).lower()
        if term.lower() in combined:
            origin = "source_file_or_prior_artifact"
        trace_entries.append({
            "forbidden_term": term,
            "origin": origin,
            "domain": domain_key,
            "recommended_action": "Remove from CER body or add to exception_contexts",
        })
    return {
        "entries": trace_entries,
        "forbidden_term_count": len(trace_entries),
        "domain": domain_key,
    }


# ── Gate 6: Claim/BR-to-Text Consistency ─────────────────────────────────────


def evaluate_claim_br_text_consistency_gate(
    cer_body_text: str,
    claim_support_matrix: dict[str, Any] | None = None,
    benefit_risk_ledger: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Gate 6: Verify CER body does not contradict claim/BR ledger."""
    findings = []
    text_lower = cer_body_text.lower()

    # Check claim consistency
    if claim_support_matrix:
        for claim_id, row in claim_support_matrix.items():
            if not isinstance(row, dict) or not claim_id.startswith("C-"):
                continue
            support = str(row.get("support_level") or row.get("support_status") or "").upper()
            conclusion = str(row.get("max_conclusion_strength") or row.get("conclusion_strength") or "").upper()
            if support in {"INSUFFICIENT", "ALLOWED_USE_BLOCKED"} or conclusion in {"NOT_ALLOWED", "INSUFFICIENT"}:
                claim_pattern = claim_id.lower()
                if claim_pattern in text_lower:
                    nearby = _extract_nearby_text(cer_body_text, claim_id, 300)
                    overclaim_signals = [
                        "supported by", "demonstrates", "confirms", "proves",
                        "sufficient evidence", "robust evidence", "strong evidence",
                        "favourable benefit", "clinical benefit is", "device is safe and effective",
                    ]
                    for signal in overclaim_signals:
                        if signal in nearby.lower():
                            findings.append({
                                "claim_id": claim_id,
                                "support_level": support,
                                "contradiction": f"Claim marked {support} but text contains '{signal}'",
                                "context": nearby[:200],
                                "severity": "HARD_FAIL",
                            })

    # Check BR ledger consistency
    if benefit_risk_ledger:
        for row in benefit_risk_ledger:
            balance = str(row.get("benefit_risk_balance") or "").lower()
            guard = str(row.get("conclusion_guard_result") or "").lower()
            if "unfavourable" in balance or "not supported" in guard or "unfavorable" in balance:
                if any(signal in text_lower for signal in [
                    "favourable benefit-risk", "favorable benefit-risk",
                    "positive benefit-risk", "overall clinical benefit is confirmed",
                    "device is considered safe and effective",
                ]):
                    findings.append({
                        "balance": balance,
                        "guard": guard,
                        "contradiction": "BR ledger shows unfavourable/not-supported but text implies favourable",
                        "severity": "HARD_FAIL",
                    })
                    break

    hard_fail = len(findings) > 0
    return {
        "gate": "Gate 6 — Claim/BR Text Consistency",
        "gate_id": "WRITER_GATE_06",
        "status": "HARD_FAIL" if hard_fail else "PASS",
        "finding_count": len(findings),
        "findings": findings,
        "quarantine": hard_fail,
        "message": (
            f"HARD_FAIL: {len(findings)} claim/BR-to-text contradiction(s) found."
            if hard_fail
            else "PASS: CER body consistent with claim/BR ledger."
        ),
    }


def _extract_nearby_text(text: str, target: str, window: int) -> str:
    idx = text.lower().find(target.lower())
    if idx < 0:
        return ""
    start = max(0, idx - window // 2)
    end = min(len(text), idx + len(target) + window // 2)
    return text[start:end]


def run_all_writer_gates(
    cer_body_text: str,
    device_profile: dict[str, Any] | None = None,
    claim_support_matrix: dict[str, Any] | None = None,
    benefit_risk_ledger: list[dict[str, Any]] | None = None,
    state: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run all writer remediation gates (1-6) against CER body text.

    Returns a combined result with per-gate status and an overall pass/fail.
    """
    gate1 = evaluate_device_domain_consistency_gate(cer_body_text, device_profile)
    gate2 = evaluate_ifu_consumption_gate(cer_body_text, device_profile)
    gate3 = evaluate_evidence_conclusion_gate(cer_body_text, claim_support_matrix)
    gate4 = evaluate_body_cleanliness_gate(cer_body_text)
    gate5 = evaluate_render_boundary_gate(cer_body_text)
    gate6 = evaluate_claim_br_text_consistency_gate(cer_body_text, claim_support_matrix, benefit_risk_ledger)

    gates = [gate1, gate2, gate3, gate4, gate5, gate6]
    any_hard_fail = any(g.get("status") == "HARD_FAIL" for g in gates)
    any_blocked = any(g.get("status") == "BLOCKED" for g in gates)
    quarantined = any(g.get("quarantine") for g in gates)

    # S6 fix: also check writer invocation and blocker status
    state = state or {}
    blocker = state.get("blocker_report") or {}
    writer_invoked = blocker.get("writer_invoked", True)

    contamination_trace = build_context_contamination_trace(cer_body_text, device_profile, state) if device_profile else {}

    if any_hard_fail:
        overall = "HARD_FAIL"
    elif any_blocked or not writer_invoked:
        overall = "BLOCKED_WITH_COMPROMISE"
    elif quarantined:
        overall = "PASS_WITH_QUARANTINE"
    else:
        overall = "PASS"
    return {
        "overall_status": overall,
        "quarantine": quarantined,
        "gates": {
            "gate_1_domain_consistency": gate1,
            "gate_2_ifu_consumption": gate2,
            "gate_3_evidence_conclusion": gate3,
            "gate_4_body_cleanliness": gate4,
            "gate_5_render_boundary": gate5,
            "gate_6_claim_br_consistency": gate6,
        },
        "context_contamination_trace": contamination_trace,
        "message": (
            "One or more writer gates HARD_FAIL; report must be quarantined."
            if quarantined
            else "All writer gates PASS; report may proceed to release candidate."
        ),
    }


# ── W3: QA Gate Hardening (Gate 5) ─────────────────────────────────────────


def evaluate_remediated_qa_gate(
    cer_body_text: str,
    device_profile: dict[str, Any] | None = None,
    claim_support_matrix: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Gate 5: Remediated QA gate — replaces Annex J / benchmark-style QA.

    Runs domain consistency, forbidden terms, evidence-conclusion consistency,
    internal language leakage, and IFU placeholder checks. Produces per-item
    findings. Never outputs score 100 / findings empty on contaminated reports.

    Returns a structured QA report: {status, score, dimensions, findings, message}
    """
    gate1 = evaluate_device_domain_consistency_gate(cer_body_text, device_profile)
    gate2 = evaluate_ifu_consumption_gate(cer_body_text, device_profile)
    gate3 = evaluate_evidence_conclusion_gate(cer_body_text, claim_support_matrix)
    gate4 = evaluate_body_cleanliness_gate(cer_body_text)

    dimensions = {
        "domain_consistency": {
            "label": "Device Domain Body Consistency",
            "status": _qa_dimension_status(gate1),
            "findings": gate1.get("findings", []),
            "warnings": gate1.get("warnings", []),
        },
        "evidence_conclusion_consistency": {
            "label": "Evidence-to-Conclusion Consistency",
            "status": _qa_dimension_status(gate3),
            "findings": gate3.get("findings", []),
            "negated_pass": gate3.get("negated_pass_count", 0),
        },
        "ifu_consumption": {
            "label": "IFU Fact Consumption",
            "status": _qa_dimension_status(gate2),
            "placeholder_count": gate2.get("placeholder_count", 0),
            "has_ifu_source": gate2.get("has_ifu_source", False),
        },
        "body_cleanliness": {
            "label": "Submission Body Cleanliness",
            "status": _qa_dimension_status(gate4),
            "findings": gate4.get("findings", []),
        },
    }

    all_findings: list[dict] = []
    for dim_key, dim in dimensions.items():
        for f in dim.get("findings", []):
            f_with_dim = dict(f)
            f_with_dim["dimension"] = dim_key
            all_findings.append(f_with_dim)

    hard_fail_dims = [k for k, d in dimensions.items() if d["status"] == "FAIL"]
    warning_dims = [k for k, d in dimensions.items() if d["status"] == "WARNING"]
    pass_dims = [k for k, d in dimensions.items() if d["status"] == "PASS"]
    skipped_dims = [k for k, d in dimensions.items() if d["status"] == "SKIPPED"]

    if hard_fail_dims:
        overall_status = "FAIL"
        score = max(0, 100 - len(hard_fail_dims) * 25)
    elif warning_dims:
        overall_status = "PASS"
        score = max(70, 100 - len(warning_dims) * 10)
    elif skipped_dims:
        overall_status = "PASS"
        score = 80
    else:
        overall_status = "PASS"
        score = 100

    return {
        "gate": "Gate 5 — Remediated QA (Content + Domain + Evidence + Cleanliness)",
        "gate_id": "WRITER_GATE_05",
        "status": overall_status,
        "score": score,
        "dimensions": dimensions,
        "failing_dimensions": hard_fail_dims,
        "warning_dimensions": warning_dims,
        "total_findings": len(all_findings),
        "hard_fail_findings": len([f for f in all_findings if f.get("triggers_fail", True)]),
        "findings": all_findings[:50],  # Cap at 50 for report size
        "quarantine": len(hard_fail_dims) > 0,
        "message": _qa_message(overall_status, hard_fail_dims, warning_dims, score),
    }


def _qa_dimension_status(gate_result: dict[str, Any]) -> str:
    """Map a gate result to a QA dimension status."""
    status = gate_result.get("status", "SKIPPED")
    if status == "HARD_FAIL":
        return "FAIL"
    if status == "PASS":
        if gate_result.get("warnings"):
            return "WARNING"
        return "PASS"
    return "SKIPPED"


def _qa_message(
    overall_status: str,
    failing_dims: list[str],
    warning_dims: list[str],
    score: int,
) -> str:
    """Build a human-readable QA message."""
    if overall_status == "FAIL":
        return (
            f"QA FAIL (score {score}): "
            f"{len(failing_dims)} dimension(s) failed — {', '.join(failing_dims)}. "
            f"Report is NOT ready for release."
        )
    if overall_status == "PASS_WITH_WARNINGS":
        return (
            f"QA PASS with warnings (score {score}): "
            f"{len(warning_dims)} dimension(s) have warnings — {', '.join(warning_dims)}."
        )
    if overall_status == "PASS_WITH_SKIPS":
        return f"QA PASS with skips (score {score}): some checks could not run."
    return f"QA PASS (score {score}): All content and domain checks passed."


# ── Helpers ─────────────────────────────────────────────────────────────────


def _find_annex_boundary(text: str) -> int:
    """Find where Annex sections start in the CER body.

    Returns the character position of the first Annex heading, or -1 if not found.
    """
    annex_patterns = [
        r"\n#+\s*Annex\s",
        r"\nAnnex\s+[A-Z]",
        r"\n#+\s*附录\s",
    ]
    for pat in annex_patterns:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            return m.start()
    return -1


def _is_exception_context(surrounding: str, term: str, exception_contexts: list[str]) -> bool:
    """Check if a forbidden term appears in an exclusion/contrast context."""
    surrounding_lower = surrounding.lower()
    # Search exclusion clauses (NOT (term1 OR term2 OR ...))
    if re.search(r"\bnot\s*\([^)]*" + re.escape(term) + r"[^)]*\)", surrounding_lower):
        return True
    # Also check for broader search-query context: if the term appears in a line
    # that contains search-result or search-strategy markers
    if any(marker in surrounding_lower for marker in (
        "| count ", "| returned ", "search-sota", "search-due",
        "not (", "not(", "search strategy", "search-strategy",
        "| pubmed |", "| clinicaltrials", "| embase", "| cochrane",
        "search_run_registry", "search protocol",
    )):
        return True
    for ec in exception_contexts:
        if ec.lower() in surrounding_lower:
            ec_idx = surrounding_lower.find(ec.lower())
            term_idx = surrounding_lower.find(term.lower())
            if abs(ec_idx - term_idx) <= 80:
                return True
    return False


def _guess_section(text: str, pos: int) -> str:
    """Guess which CER section a position falls in."""
    # Look backward for the nearest markdown heading
    before = text[:pos]
    heading_matches = list(re.finditer(r"^#{1,4}\s+(.+)$", before, re.MULTILINE))
    if heading_matches:
        return heading_matches[-1].group(1).strip()[:80]
    return "(preamble)"


def _extract_section(text: str, section_label: str) -> str | None:
    """Extract a named section from CER markdown body.

    Finds a markdown heading (line starting with #) that contains the section label,
    then returns all text from that heading to the next heading of equal or higher level.
    """
    label_lower = section_label.lower()
    lines = text.split("\n")
    start_idx = None
    heading_level = 0

    # Find the heading line
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("#") and label_lower in stripped.lower():
            # Count heading level
            heading_level = len(stripped) - len(stripped.lstrip("#"))
            start_idx = i
            break

    if start_idx is None:
        return None

    # Extract from heading to next heading of same or higher level
    end_idx = len(lines)
    for i in range(start_idx + 1, len(lines)):
        stripped = lines[i].strip()
        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            if level <= heading_level:
                end_idx = i
                break

    extracted = "\n".join(lines[start_idx:end_idx])
    return extracted[:5000]


def _worst_support_level(matrix: dict[str, Any]) -> str | None:
    """Extract the most restrictive support_level from a claim_support_matrix.

    Priority: INSUFFICIENT > CAUTIOUS > MODERATE > STRONG
    """
    LEVEL_RANK = {"INSUFFICIENT": 0, "CAUTIOUS": 1, "MODERATE": 2, "STRONG": 3}

    worst: str | None = None
    worst_rank = 99

    # Skip metadata keys
    SKIP_KEYS = {"retrieval_completeness", "schema_name", "provisional_mode"}

    for key, claim in matrix.items():
        if key in SKIP_KEYS or not isinstance(claim, dict):
            continue
        sl = claim.get("support_level") or claim.get("max_conclusion_strength")
        if sl:
            level = resolve_policy_level(str(sl))
            if level:
                rank = LEVEL_RANK.get(level, 99)
                if rank < worst_rank:
                    worst_rank = rank
                    worst = str(sl)

    return worst
